export const FETCH_WEATHER = "COMMAND/FETCH_WEATHER_FOR_LAT_LNG";
export const API_ERROR = "EVENT/API_ERROR_RECEIVED";
export const WEATHER_DATA_RECEIVED = "EVENT/WEATHER_DATA_RECEIVED";
export const WEATHER_ID_RECEIVED = "EVENT/WEATHER_ID_RECEIVED";

export const FETCH_DRONES = "COMMAND/FETCH_DRONES";
export const NEXT_DRONE = "COMMAND/NEXT_DRONE";
export const PREV_DRONE = "COMMAND/PREV_DRONE";

export const DRONE_DATA_RECIEVED = "EVENT/DRONE_DATA_RECIEVED";